image: maven:3.8-openjdk-11-slim

stages:
  - build
  - test
  - release

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository "

package:
  stage: build
  script:
    - mvn -DskipTests package

unit-test:
  stage: test
  script:
    - mvn test

docker-image:
  stage: release
  only:
    - main
  script:
    - docker build -t SecurityService:latest .
    - docker tag jdqc.local:5000/SecurityService:latest
    - docker push jdqc.local:5000/SecurityService:latest

