stages:
  - build
  - test
  - release
  - deploy

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository "
  TARGET_IMAGE: $REGISTRY_ADDR/jdqc/security-service:latest

package:
  stage: build
  image: maven:3.8-openjdk-11-slim
  script:
    - mvn -DskipTests package
  artifacts:
    paths:
      - target/

unit-test:
  stage: test
  image: maven:3.8-openjdk-11-slim
  script:
    - mvn test

docker-image:
  stage: release
  tags:
    - builder
  only:
    - main
  before_script:
    - docker info
  script:
    - docker pull $TARGET_IMAGE || true # for docker build caching if allowed
    - docker build --cache-from $TARGET_IMAGE --tag $TARGET_IMAGE .
    - docker push $TARGET_IMAGE