spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: Security
    url:
    username:
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    database: mysql
  redis:
    host: "127.0.0.1"
